### PR TITLE
Content: Update images for community and editor sections

### LINKED ISSUE #87: Community photo has wrong grey color
color

> The gray color in the WebP compressed “Community Photo” is off from the gray below. I’ve provided a new PNG, but I suspect it’s in the scaling down, or the conversion to webp that the color artifacts come, so I’d be happy to pair on getting this right.

New photo, will need to be optimized/converted to webp, make sure the color doesn't change.
Community Photo

### LINKED ISSUE #88: Editor photo is not high-resolution
Screenshot 2022-08-15 at 18 26 58

> The background image behind “Dream it, build it”, is low resolution. Have separately provided a new image.

New image, will need to be optimized/converted to webp.
Editor

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #87, fixes #88. This updates two of the images on the homepage with new ones that don't have compression issues. They've been converted from PNG to webp with a quality of 90, and visually appear the same. The color of the stroke on the community image did not change, so it should blend into the following section.

### Screenshots

| Before | After |
|--------|-------|
|  |  |
|  |  |

### How to test the changes in this Pull Request:

1. View the homepage
2. The editor image should not be fuzzy/pixelated
3. The community image should be seamless with the content after it

### CODE REVIEW

File: source/wp-content/themes/wporg-main-2022/patterns/front-page.php [hunk 1]
```diff
@@ -191,8 +191,8 @@
...
+<div class="wp-block-cover alignfull is-light" style="margin-bottom:60px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;min-height:500px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim"></span><img class="wp-block-cover__image-background wp-image-11557" alt="A black and white bird’s eye view of the thousands of contributors who attended WordCamp Europe 2022. They are all standing in front of the venue with their hands up in celebration." src="https://wordpress.org/files/2022/08/Community-Photo.webp" style="object-position:50% 100%" data-object-fit="cover" data-object-position="50% 100%"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","fontSize":"large"} -->
```
Comment (adamwoodnz) [inline source/wp-content/themes/wporg-main-2022/patterns/front-page.php]: I'm still seeing a very slight difference between the image and section below:

Kapture 2022-08-17 at 09 57 56

File: source/wp-content/themes/wporg-main-2022/patterns/front-page.php [hunk 2]
```diff
@@ -34,8 +34,8 @@
...
 
-<!-- wp:cover {"url":"https://wordpress.org/files/2022/08/editor-bg-scaled-1.webp","id":11480,"dimRatio":0,"minHeight":670,"minHeightUnit":"px","isDark":false,"align":"full","style":{"spacing":{"padding":{"top":"80px","right":"0px","bottom":"80px","left":"0px"}}}} -->
-<div class="wp-block-cover alignfull is-light" style="padding-top:80px;padding-right:0px;padding-bottom:80px;padding-left:0px;min-height:670px" id="editor"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim"></span><img class="wp-block-cover__image-background wp-image-11480" alt="" src="https://wordpress.org/files/2022/08/editor-bg-scaled-1.webp" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"style":{"elements":{"link":{"color":{"text":"var:preset|color|blueberry-2"}}}},"textColor":"white","layout":{"inherit":false,"contentSize":"520px"}} -->
+<!-- wp:cover {"url":"https://wordpress.org/files/2022/08/Editor.webp","id":11557,"dimRatio":0,"minHeight":670,"minHeightUnit":"px","isDark":false,"align":"full","style":{"spacing":{"padding":{"top":"80px","right":"0px","bottom":"80px","left":"0px"}}}} -->
```
Comment (adamwoodnz) [inline source/wp-content/themes/wporg-main-2022/patterns/front-page.php]: I think we'll need to update the lazy loading filter with this name change, see https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/themes/wporg-main-2022/functions.php#L97

Comment (ryelle) [reply source/wp-content/themes/wporg-main-2022/patterns/front-page.php]: oh, good catch 👍🏻

**Review by adamwoodnz — COMMENTED** [review]
Editor image LGTM. See a couple of comments inline 🙂

File: source/wp-content/themes/wporg-main-2022/patterns/front-page.php (hunk 1 above)
Comment (ryelle) [reply source/wp-content/themes/wporg-main-2022/patterns/front-page.php]: It looks like this hex color is set on the group itself, not using the preset color `light-grey-2`. I'll fix that, but `light-grey-2` _is_ `#f6f6f6`, so it'll still be different… 🤔 

I think this section is using the wrong grey color in figma. @jasmussen Could you create a new image with the grey as `#f6f6f6`?

Comment (jasmussen) [reply source/wp-content/themes/wporg-main-2022/patterns/front-page.php]: Thanks so much for the PR. The "Dream it" background looks way better. Yes I'm also seeing the color slightly off, which is curious because the light-grey-2 as defined in the Figma file _should_ be f6f6f6. Nevertheless, I think this image might thread the needle.
Community Photo

I presume this gets recompressed, so I provided as a PNG. Let me know if you need anything else.
