### PR TITLE
Fix export of content with list items

### LINKED ISSUE #177: Export content parser doesn't handle rich text content in list items
List items (like those in the About/Features page) which contain rich text elements such as `a`, `strong`, `br`, tags are not parsed correctly when exporting the content to a pattern via `yarn build:patterns`. The resulting pattern is broken, will not load in the editor and fails PHP lint.

**To Reproduce**
1. Add a page at `/about-2/features-2/` to your site and the following to page-manifest.json
```
{
		"slug": "features-2",
		"pattern": "features.php",
		"template": "page-features.html"
	},
```
2. Run `yarn build:patterns`
3. Inspect the markup of the generated file `features.php` and observe that the inner HTML has been replaced incorrectly in list items which have rich text content, for example `a`, `strong`, `br`, tags.

Example input markup
```
<!-- wp:list-item -->
<li><strong>Theme System</strong><br>Create WordPress themes for clients, other WordPress users, or yourself. WordPress provides the extensibility to <a href="https://developer.wordpress.org/themes/">create themes</a> as simple or as complex as you wish. If you want to give your theme away for free you can give it to users in the <a href="https://wordpress.org/themes/">theme repository</a>.</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><strong>Application Framework</strong><br>If you want to build an application, WordPress can help with that too. WordPress provides a lot of the features under the hood that your app will need: translations, user management, HTTP requests, databases, URL routing and much, much more. You can also use our <a href="https://developer.wordpress.org/rest-api/">REST API</a> to interact with it.</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><strong>Custom Content Types</strong><br>WordPress comes with default content types, but for more flexibility you can add a few lines of code to create your own <a href="https://developer.wordpress.org/plugins/post-types/">custom post types</a>, <a href="https://developer.wordpress.org/plugins/taxonomies/">taxonomies</a>, and <a href="https://developer.wordpress.org/plugins/metadata/">metadata</a>. Take WordPress in whatever direction you wish.</li>
<!-- /wp:list-item -->
```

Output markup
```
<!-- wp:list-item -->
<li><strong><?php _e( 'Theme System', 'wporg' ); ?></strong><br><?php _e( 'Create WordPress themes for clients, other WordPress users, or yourself<?php _e( '.', 'wporg' ); ?> WordPress provides the extensibility to ', 'wporg' ); ?><a href="https://developer<?php _e( '.', 'wporg' ); ?>wordpress<?php _e( '.', 'wporg' ); ?>org/themes/"><?php _e( 'create themes', 'wporg' ); ?></a><?php _e( ' as simple or as complex as you wish<?php _e( '.', 'wporg' ); ?> If you want to give your theme away for free you can give it to users in the ', 'wporg' ); ?><a href="https://wordpress<?php _e( '.', 'wporg' ); ?>org/themes/"><?php _e( 'theme repository', 'wporg' ); ?></a><?php _e( '.', 'wporg' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><strong><?php _e( 'Application Framework', 'wporg' ); ?></strong><br><?php _e( 'If you want to build an application, WordPress can help with that too. WordPress provides a lot of the features under the hood that your app will need: translations, user management, HTTP requests, databases, URL routing and much, much more. You can also use our ', 'wporg' ); ?><a href="https://developer.wordpress.org/rest-api/"><?php _e( 'REST API', 'wporg' ); ?></a><?php _e( ' to interact with it.', 'wporg' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><strong><?php _e( 'Custom Content Types'<?php _e( ', ', 'wporg' ); ?>'wporg' ); ?></strong><br><?php _e( 'WordPress comes with default content types<?php _e( ', ', 'wporg' ); ?>but for more flexibility you can add a few lines of code to create your own '<?php _e( ', ', 'wporg' ); ?>'wporg' ); ?><a href="https://developer.wordpress.org/plugins/post-types/"><?php _e( 'custom post types'<?php _e( ', ', 'wporg' ); ?>'wporg' ); ?></a><?php _e( ', ', 'wporg' ); ?><a href="https://developer.wordpress.org/plugins/taxonomies/"><?php _e( 'taxonomies', 'wporg' ); ?></a><?php _e( ', ', 'wporg' ); ?>and <a href="https://developer.wordpress.org/plugins/metadata/"><?php _e( 'metadata', 'wporg' ); ?></a><?php _e( '. Take WordPress in whatever direction you wish.', 'wporg' ); ?></li>
<!-- /wp:list-item -->
```

Editor screenshot
Screen Shot 2023-01-26 at 5 10 13 PM

**Expected behavior**
Rich text content in list items is parsed in the same way as it is for paragraphs

### PR DESCRIPTION
**Pull request by adamwoodnz**
Incremental improvement to parsing list items. Currently if they contain other tags (eg. strong, em, a) the output markup in the resulting pattern file is broken. This PR copies the parser for paragraphs, changes the regex from `p` to `li`, and updates already exported patterns. 

Fixes #177 

Props @tellyworth , @StevenDufresne 

### How to test the changes in this Pull Request:

1. Add a page `/about-2/features-2/` to your site and the following to `page-manifest.json`
```
{
	"slug": "features-2",
	"pattern": "features.php",
	"template": "page-features.html"
},
```
and this to your `theme-switcher.php`
```
'/about-2/',
'/about-2/features-2/',
```
2. Run `yarn build:patterns`
3. Inspect the markup of the generated file `features.php` and observe that the markup in `patterns/features.php` is valid PHP, and text is escaped for translation. In particular check the output of `li` tags which include `a`, `strong`, `br`, tags. It should be consistent with the output of `p` tags.
4. For the page `/about-2/features-2/` choose the Features page template and run the page. There should be no fatal and the page should display like prod.

### CODE REVIEW

File: source/wp-content/themes/wporg-main-2022/patterns/download-source.php [hunk 1]
```diff
@@ -35,11 +35,11 @@
 
 <!-- wp:list -->
 <ul><!-- wp:list-item -->
-<li><?php _e( 'Subversion: ', 'wporg' ); ?><code><?php _e( 'https://core.svn.wordpress.org/', 'wporg' ); ?></code></li>
+<li><?php _e( 'Subversion: <code>https://core.svn.wordpress.org/</code>', 'wporg' ); ?></li>
```
Comment (tellyworth) [inline source/wp-content/themes/wporg-main-2022/patterns/download-source.php]: Are these changes intended? I think it needs some discussion to decide if it's an improvement to the output translation strings or not.

**Comment by iandunn** [comment]
This might be a good reason to add some unit tests for the parser. We could start with the example that's fixed in this PR, and maybe a few easy ones.

https://github.com/WordPress/wporg-two-factor has some boilerplate you could copy to get started.

File: source/wp-content/themes/wporg-main-2022/patterns/download-source.php (hunk 1 above)
Comment (adamwoodnz) [reply source/wp-content/themes/wporg-main-2022/patterns/download-source.php]: Yeah it's a fair question, that's the way paragraphs are handled at the moment. I assumed that was acceptable to translators. I'll take a look at @dd32's [updated parsers](https://github.com/WordPress/wordpress.org/pull/90) and see if they improve this

**Comment by adamwoodnz** [comment]
> This might be a good reason to add some unit tests for the parser.

Yes, I was planning to take a look at the existing tests mentioned in the code `// todo: this needs a fix to properly rebuild innerContent - see ParagraphParserTest`, but it looks like they weren't copied in with the parser

File: source/wp-content/themes/wporg-main-2022/patterns/download-source.php (hunk 1 above)
Comment (adamwoodnz) [reply source/wp-content/themes/wporg-main-2022/patterns/download-source.php]: I tried using the [HTMLParser](https://github.com/WordPress/wordpress.org/blob/43a932859f59fb69dd46d08eb582d4c631b579fc/wordpress.org/public_html/wp-content/plugins/glotpress-translate-bridge/inc/parsers/HTMLParser.php) but it doesn't seem to be just a 'drop in' fix.

**Comment by adamwoodnz** [comment]
I've created a new [issue](https://github.com/WordPress/wporg-main-2022/issues/179) for the tests, as I'm still struggling to get them bootstrapped and I want to get the About pages and merged for final review. I'm going to merge this incremental improvement and we can improve HTML parsing moving forward.

File: source/wp-content/themes/wporg-main-2022/patterns/download-source.php (hunk 1 above)
Comment (adamwoodnz) [reply source/wp-content/themes/wporg-main-2022/patterns/download-source.php]: Backed out of the updates here. We'll iterate on the parser in #181 so that links aren't required to be translated
